# Generated by Django 4.1 on 2022-08-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Em desenvolvimento', max_length=200),
            preserve_default=False,
        ),
    ]
